import esbuild from "esbuild";
import process from "process";
import { builtinModules as builtins } from "node:module";
import fs from "fs";
import path from "path";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");
const userProfile = process.env.USERPROFILE || "C:\\Users\\Jamet";
const primaryVaultPluginDir = path.join(userProfile, "Documents", "VoiceNotes", ".obsidian", "plugins", "obsidian-dynamic-slides");
const fallbackVaultPluginDir = "C:\\Users\\hjamet\\Documents\\VoiceNotes\\.obsidian\\plugins\\obsidian-dynamic-slides";

function copyToVault() {
	const dirs = [primaryVaultPluginDir];
	if (fallbackVaultPluginDir !== primaryVaultPluginDir && fs.existsSync("C:\\Users\\hjamet\\Documents\\VoiceNotes")) {
		dirs.push(fallbackVaultPluginDir);
	}

	for (const dir of dirs) {
		try {
			if (!fs.existsSync(dir)) {
				fs.mkdirSync(dir, { recursive: true });
			}
			const filesToCopy = ["main.js", "manifest.json", "styles.css"];
			for (const file of filesToCopy) {
				if (fs.existsSync(file)) {
					fs.copyFileSync(file, path.join(dir, file));
				}
			}
			console.log(`[esbuild] Copied build outputs to ${dir}`);
		} catch (err) {
			console.error(`[esbuild] Error copying files to ${dir}:`, err);
		}
	}
}

const copyPlugin = {
	name: "copy-to-vault-plugin",
	setup(build) {
		build.onEnd((result) => {
			if (result.errors.length === 0) {
				copyToVault();
			}
		});
	},
};

const context = await esbuild.context({
	banner: { js: banner },
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins
	],
	format: "cjs",
	target: "es2021",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	plugins: [copyPlugin],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
